### PR TITLE
fix: incomplete github repositories list into modal

### LINKED ISSUE #91: [Bug]: Incomplete GitHub repositories list
### Description

Only repositories repositories from the PoC Innovation organization can be selected :frowning_face: 

### What happened?

When you sign in with GitHub OAuth, the user repositories don't appear in the list.

### Expected behaviour

You should be able to select public and private repositories of the user, not (or not only) the PoC repositories.

### Environment

- `master`

### Steps to reproduce

- Sign in with GitHub OAuth
- Try to select a repository

### Relevant log output

_No response_

### Proposed solution

Take a look at the OAuth scopes, the app is hosted on the PoC Innovation organization, it works perfectly fine for apps on personal accounts.

### PR DESCRIPTION
**Pull request by lucas-louis**
# Description

- Add multi pages management
- Update frontend to display multi pages

Close #91

# Changes include

- [X] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to an issue
- [X] I have linked this PR to a milestone
- [X] I have linked this PR to a project
- [X] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

File: src/components/computing/github/GithubModal.tsx [hunk 1]
```diff
@@ -108,16 +122,32 @@ const GithubModal = ({ isOpen, onClose }: { isOpen: boolean; onClose: () => void
...
-							>
-								{repositories.map((repository, index: number) => (
-									<option key={index} value={repository.html_url}>
-										{repository.name}
-									</option>
-								))}
-							</Select>
+							<VStack w="100%">
+								<HStack justify="space-between" w="100%">
+									<Text>Dont see your repository?</Text>
```
Comment (RezaRahemtola) [inline src/components/computing/github/GithubModal.tsx:127]: What is this for?

**Review by RezaRahemtola — APPROVED** [review]
Really cool :fire: 

It could be even better with a search bar instead of the page switch / select, for example in my case I have 8 pages which is quite unpleasant to navigate :wink:
